# Generated by Django 4.2.7 on 2023-11-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='password',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
