# Generated by Django 5.0.2 on 2024-02-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_judge_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='password',
        ),
    ]
