# Generated by Django 4.2.7 on 2023-11-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('birthdate', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('hobbies', models.CharField(help_text='Add subjects separated with ","', max_length=255)),
                ('avatar', models.ImageField(upload_to='competitor')),
                ('active', models.BooleanField()),
                ('music_style', models.ManyToManyField(to='program.musicstyle')),
                ('subject', models.ManyToManyField(to='program.subject')),
            ],
        ),
    ]
