# Generated by Django 5.0.2 on 2024-02-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0002_alter_competitor_job_alter_competitor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='nominated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
